apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: local-pv-test-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: local-pv-test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: reader
        image: busybox
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - "tail -f /usr/test-pod/test_file"
        volumeMounts:
        - name: local-vol
          mountPath: /usr/test-pod
      volumes:
      - name: local-vol
        persistentVolumeClaim: 
          claimName: "my-pvc"
