kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: local-pv-test-pod
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: my-pvc
