apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
      "requiredDuringSchedulingIgnoredDuringExecution": {
        "nodeSelectorTerms": [
          { "matchExpressions": [
              { "key": "kubernetes.io/hostname",
                "operator": "In",
                "values": ["192.168.152.134"]
              }   
            ]}  
        ]}  
      }'
spec:
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/sky-big/work/k8s-storage
